import "./globals.css";
import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";

const openSansFont = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Dadacord",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={openSansFont.className}>{children}</body>
    </html>
  );
}
